import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"
import {
    createOnboardingStepV2,
} from "../lib/onboarding/block-definition.ts"

const builderPage = readFileSync("app/[workspaceSlug]/onboarding-builder/page.tsx", "utf8")
const builderUi = readFileSync("components/onboarding-builder/OnboardingBuilderWorkspace.tsx", "utf8")
const blockValidation = readFileSync("lib/onboarding/block-validation.ts", "utf8")
const blockLayout = readFileSync("lib/onboarding/block-layout.ts", "utf8")
const collaboration = readFileSync("components/onboarding-builder/useCollaborativeOnboardingDocument.ts", "utf8")
const visualActions = readFileSync("app/[workspaceSlug]/onboarding-builder/visual-actions.ts", "utf8")
const visualCanvas = readFileSync("components/onboarding-builder/VisualBuilderCanvas.tsx", "utf8")
const runtimeBlocks = readFileSync("components/onboarding/OnboardingBlocks.tsx", "utf8")
const runtimePage = readFileSync("app/onboarding/session/[token]/page.tsx", "utf8")
const previewPage = readFileSync("app/onboarding/preview/[token]/page.tsx", "utf8")
const workspaceShell = readFileSync("components/workspace/WorkspaceTopBarClient.tsx", "utf8")
const onboardingSettings = readFileSync("components/settings/OnboardingSettings.tsx", "utf8")
const brandingSettings = readFileSync("components/settings/AgencyBrandingEditor.tsx", "utf8")
const migration = readFileSync("supabase/migrations/20260810110000_visual_onboarding_builder_v2.sql", "utf8")

test("version-two steps use a protected Header and compatible mixed blocks", () => {
    const ordinary = createOnboardingStepV2()
    const bookend = createOnboardingStepV2({ bookend: true })
    assert.deepEqual(ordinary.blocks.map((block) => block.kind), ["header", "form"])
    assert.deepEqual(bookend.blocks.map((block) => block.kind), ["header"])
    assert.match(blockValidation, /Every step needs exactly one Header block/)
    assert.match(blockValidation, /Welcome and Completion steps cannot contain forms/)
    assert.match(blockValidation, /A step can contain only one Form block/)
})

test("publish validation rejects unsafe V2 definitions", () => {
    assert.match(blockValidation, /Replace embedded videos with a workspace upload before publishing/)
    assert.match(blockValidation, /The Header must remain the first block in every step/)
    assert.match(blockValidation, /Block IDs must be unique within a definition/)
    assert.match(blockValidation, /Field IDs must be unique within a definition/)
    assert.match(blockValidation, /Button destinations must use HTTPS/)
    assert.match(blockLayout, /spacingBeforeClasses/)
    assert.match(blockLayout, /spacingAfterClasses/)
})

test("the visual Builder is standalone, responsive, collapsible, and composition-driven", () => {
    assert.match(builderPage, /requireWorkspace\(workspaceSlug, "admin"\)/)
    assert.match(builderPage, /h-dvh/)
    assert.match(builderPage, /visualEnabled/)
    assert.match(workspaceShell, /panel\.standalone/)
    assert.match(workspaceShell, /window\.open\(href, "_blank", "noopener,noreferrer"\)/)
    assert.match(onboardingSettings, /target="_blank"/)
    assert.match(builderUi, /resolveOrderedModuleSources/)
    assert.match(builderUi, /betelgeze:onboarding-builder:/)
    assert.match(builderUi, /Collapse left rail/)
    assert.match(builderUi, /Collapse right rail/)
    assert.match(visualCanvas, /max-w-\[430px\]/)
    assert.match(builderUi, /Calendar/)
    assert.match(builderUi, /Coming later/)
})

test("structural authoring supports library drag, cross-definition moves, duplication, and phone restrictions", () => {
    assert.match(builderUi, /application\/x-betelgeze-builder-item/)
    assert.match(builderUi, /type: "library"/)
    assert.match(builderUi, /event\.shiftKey/)
    assert.match(builderUi, /linkedChangeSets/)
    assert.match(builderUi, /A step containing a Form cannot be moved into a bookend/)
    assert.match(builderUi, /Each bookend must retain at least one step/)
    assert.match(builderUi, /hidden md:flex/)
    assert.match(visualCanvas, /hidden w-fit md:block/)
    assert.match(visualCanvas, /application\/x-betelgeze-block/)
})

test("collaborative drafts use private Realtime, Yjs merging, presence, author undo, and fail-closed offline editing", () => {
    assert.match(collaboration, /from "yjs"/)
    assert.match(collaboration, /new Y\.UndoManager/)
    assert.match(collaboration, /KEYED_ARRAY_KIND/)
    assert.match(collaboration, /reconcileKeyedArray/)
    assert.match(collaboration, /retryUpdateRef/)
    assert.match(collaboration, /batch\.updateId/)
    assert.match(collaboration, /private: true/)
    assert.match(collaboration, /event: "document-update"/)
    assert.match(collaboration, /channel\.track/)
    assert.match(collaboration, /Offline — editing paused|offline/)
    assert.match(collaboration, /editable: \["synced", "syncing"\]/)
    assert.match(migration, /onboarding_builder_updates/)
    assert.match(migration, /append_onboarding_builder_update/)
    assert.match(migration, /on conflict \(workspace_id, update_id\) do nothing/)
    assert.match(migration, /if v_sequence is null then/)
    assert.match(migration, /floor\(extract\(epoch from now\(\)\) \/ 900\)/)
    assert.match(migration, /realtime\.topic\(\) like 'onboarding-builder:%'/)
    assert.match(migration, /public\.is_workspace_member\(workspace_id, array\['owner','admin'\]\)/)
    assert.doesNotMatch(migration, /public\.is_workspace_role/)
})

test("one release transaction publishes definitions, style, migrations, notices, and Activity", () => {
    assert.match(visualActions, /publish_visual_onboarding_release/)
    assert.match(visualActions, /p_expected_document_version/)
    assert.match(migration, /for update/)
    assert.match(migration, /save_onboarding_module_draft/)
    assert.match(migration, /publish_onboarding_module/)
    assert.match(migration, /publish_onboarding_bookend/)
    assert.match(migration, /publish_onboarding_theme_draft/)
    assert.match(migration, /onboarding_release_notices/)
    assert.match(migration, /consolidated_release_id/)
    assert.match(migration, /record_workspace_admin_activity/)
    assert.match(migration, /The Builder changed while this release was being reviewed/)
    assert.match(migration, /Completion cannot be published while an active client has already started it/)
})

test("runtime requirements persist by stable session block and gate atomic step completion", () => {
    assert.match(migration, /relationship_onboarding_session_blocks/)
    assert.match(migration, /onboarding_block_requirements/)
    assert.match(migration, /satisfy_onboarding_block_requirement/)
    assert.match(migration, /Complete the required video or link before continuing/)
    assert.match(runtimeBlocks, /onEnded=\{\(\) => void satisfy\(block, "video_finished"\)\}/)
    assert.match(runtimeBlocks, /onClick=\{\(\) => void satisfy\(block, "button_opened"\)\}/)
    assert.match(runtimeBlocks, /disabled=\{unsatisfied\.length > 0\}/)
    assert.match(runtimePage, /satisfiedBlockIds/)
    assert.match(runtimePage, /Boolean\(currentStep\.blocks\?\.length\)/)
})

test("frozen visual previews and Settings style share the release pipeline without live draft leakage", () => {
    assert.match(migration, /onboarding_visual_preview_tokens/)
    assert.match(migration, /expires_at timestamptz not null/)
    assert.match(visualActions, /Date\.now\(\) \+ 24 \* 60 \* 60 \* 1_000/)
    assert.match(migration, /p_expires_at > now\(\) \+ interval '24 hours 5 minutes'/)
    assert.match(previewPage, /onboarding_visual_preview_tokens/)
    assert.match(previewPage, /OnboardingSessionRenderer/)
    assert.match(previewPage, /preview/)
    assert.match(brandingSettings, /Unpublished style draft/)
    assert.match(brandingSettings, /publishVisualThemeDraft/)
    assert.match(builderUi, /Colour palette/)
    assert.match(builderUi, /Publishing colours immediately updates active and completed onboarding sessions/)
})
