import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

const migration = readFileSync("supabase/migrations/20260903210000_public_workspace_sms_opt_ins.sql", "utf8")
const optInPage = readFileSync("app/onboarding/smsoptin/page.tsx", "utf8")
const optInForm = readFileSync("components/onboarding/SmsOptInForm.tsx", "utf8")
const consent = readFileSync("lib/client-sales/sms-consent.ts", "utf8")
const consentState = readFileSync("lib/client-sales/sms-consent-state.ts", "utf8")
const relationshipActions = readFileSync("app/[workspaceSlug]/relationships/actions.ts", "utf8")
const relationshipPage = readFileSync("app/[workspaceSlug]/relationships/[relationshipId]/page.tsx", "utf8")
const dealWorkspace = readFileSync("app/[workspaceSlug]/relationships/[relationshipId]/RelationshipDealWorkspace.tsx", "utf8")
const omnichannel = readFileSync("lib/client-messages/omnichannel.ts", "utf8")
const saleAutomation = readFileSync("lib/client-sales/automation.ts", "utf8")
const outbox = readFileSync("lib/onboarding/outbox.ts", "utf8")
const twilioWebhook = readFileSync("app/api/client-messages/twilio/route.ts", "utf8")
const proxy = readFileSync("proxy.ts", "utf8")

test("public agency SMS opt-ins retain auditable consent independently of a sale", () => {
    assert.match(migration, /create table if not exists public\.workspace_sms_opt_ins/u)
    assert.match(migration, /submitted_name text not null/u)
    assert.match(migration, /phone_e164 text not null/u)
    assert.match(migration, /disclosure_text text not null/u)
    assert.match(migration, /consented_at timestamptz not null/u)
    assert.match(migration, /source_url text not null/u)
    assert.match(migration, /unique \(workspace_id, phone_e164\)/u)
    assert.match(migration, /workspace_sms_opt_in_id uuid/u)
    assert.match(migration, /sms_recipient_e164 text/u)
    assert.match(migration, /client_sales_pending_sms_recipient_idx/u)
})

test("the tokenless opt-in form clearly identifies the program and requires affirmative consent", () => {
    assert.match(optInPage, /What you are opting in to/u)
    assert.match(optInForm, /name="name"/u)
    assert.match(optInForm, /name="phone"/u)
    assert.match(optInForm, /name="sms_consent" type="checkbox" value="yes" required/u)
    assert.doesNotMatch(optInForm, /defaultChecked|checked=/u)
    assert.match(optInForm, /Message frequency varies/u)
    assert.match(optInForm, /Msg &amp; data rates may apply/u)
    assert.match(optInForm, /Reply HELP for help or STOP to opt out/u)
    assert.match(optInForm, /Consent is optional and is not a condition of purchase/u)
    assert.match(optInPage, /https:\/\/www\.betelgeze\.com\/privacy/u)
    assert.match(optInPage, /https:\/\/www\.betelgeze\.com\/terms/u)
    assert.doesNotMatch(optInPage + optInForm, /token/u)
})

test("verified custom onboarding domains expose /smsoptin without a token", () => {
    assert.match(proxy, /workspace\.surface === "onboarding" && path === "\/smsoptin"/u)
    assert.match(proxy, /withRewrite\(request, "\/onboarding\/smsoptin", headers\)/u)
    assert.match(proxy, /INTERNAL_WORKSPACE_HEADERS\.forEach\(\(header\) => nextHeaders\.delete\(header\)\)/u)
    assert.doesNotMatch(proxy, /sms-consent/u)
})

test("either event order sends sample one exactly once for an opted-in pending sale", () => {
    assert.match(consent, /sendPendingSaleSmsConfirmations/u)
    assert.match(consent, /sendSaleSmsConfirmationIfOptedIn/u)
    assert.match(consent, /\.in\("status", PENDING_SALE_STATUSES\)/u)
    assert.match(consent, /\.eq\("sms_recipient_e164", phoneE164\)/u)
    assert.match(consent, /You're opted in to receive SMS messages related to your client onboarding/u)
    assert.match(consent, /Reply CONFIRM to receive your secure onboarding link/u)
    assert.match(consent, /smsConsentContext: "web_opt_in"/u)
    assert.match(consent, /status: "sending_confirmation"/u)
    assert.match(saleAutomation, /smsConsentForConfirmation/u)
    assert.match(saleAutomation, /markSmsConsentConfirmed/u)
    assert.match(outbox, /Thanks for confirming\. Complete your onboarding here:/u)
})

test("selling checks the opt-in table and the relationship UI has no consent-link controls", () => {
    assert.match(relationshipActions, /if \(sale\.requiresSmsConsent\)/u)
    assert.match(relationshipActions, /sendSaleSmsConfirmationIfOptedIn/u)
    assert.match(relationshipActions, /kind: "sms"/u)
    assert.match(dealWorkspace, /Sell and send SMS/u)
    assert.match(dealWorkspace, /Client sold and waiting for SMS opt-in/u)
    assert.doesNotMatch(relationshipPage, /SMS consent|Copy SMS consent link|smsConsentUrl/u)
})

test("SMS delivery stays consent gated and STOP deactivates both consent records", () => {
    assert.match(omnichannel, /smsConsentAllowsDelivery/u)
    assert.match(consentState, /workspace_sms_opt_ins/u)
    assert.match(consentState, /status: "opted_out"/u)
    assert.match(twilioWebhook, /OptOutType/u)
    assert.match(twilioWebhook, /recordSmsOptOut/u)
    assert.doesNotMatch(twilioWebhook, /recordSmsStart/u)
    assert.match(twilioWebhook, /if \(optOutType === "HELP"\) return twimlResponse\(\)/u)
})
